[tox]
envlist = py310, py311, py312

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
passenv = TOXENV CI GITHUB_*
commands =
          pytest -v test/unit

deps =
     -r{toxinidir}/requirements.txt
     -r{toxinidir}/requirements-dev.txt
usedevelop = True
exclude = .venv,.git,.tox,docs